name: Push-to-EC2
# Trigger deployment only on push to master branch
on:
  push:
    branches:
      - dev-deploy
jobs:
  deploy:
    name: Deploy to EC2 on dev-deploy branch push
    runs-on: ubuntu-latest

    steps:  
      - name: Checkout the files
        uses: actions/checkout@v2

      - name: Deploy to Server 1
        uses: easingthemes/ssh-deploy@main
        with:
          script: |
            cd ~/2023-1a-t03-grupo4/backend/
            rm -rf node_modules
            npm install
            npm run start:dev > build.log
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: ${{ secrets.TARGET_DIR }}